Repository skarneedi/Gator-Club-Life, pull requests merged in 2025-04, with the labels that each got.

#140 Api for bookings page
  backend/main.go
  backend/routes/bookingHandlers.go
  backend/routes/bookingRoutes.go
Labels: BE, Sprint 3

#145 Fixed the Duplicate endpoint
  backend/main.go
  backend/routes/bookingHandlers.go
  backend/routes/bookingRoutes.go
  backend/routes/clubs.go
  gator_club_life.db
Labels: bug, BE, Sprint 4

#151 Added an endpoint to fetch an organization based on ID
  backend/main.go
  backend/routes/clubs.go
Labels: BE, Sprint 4

#152 Updated database and endpoints to fetch officers by organization and …
  backend/database/database.go
  backend/main.go
  backend/routes/clubs.go
  gator_club_life.db
Labels: BE, Sprint 4

#153 Updated GetAnnouncements API and database to support filtering
  backend/routes/announcements.go
  gator_club_life.db
  gator_club_life.db-journal
Labels: BE, Sprint 4

#156 Login Email Validation
  GatorClubLife/src/app/login/login.component.ts
Labels: bug, FE, Sprint 4

#158 Permits Page
  GatorClubLife/src/app/permits/permits.component.css
  GatorClubLife/src/app/permits/permits.component.html
  GatorClubLife/src/app/permits/permits.component.ts
Labels: FE, Sprint 4

#160 Events form
  GatorClubLife/src/app/app.routes.ts
  GatorClubLife/src/app/events-form/events-form.component.css
  GatorClubLife/src/app/events-form/events-form.component.html
  GatorClubLife/src/app/events-form/events-form.component.spec.ts
  GatorClubLife/src/app/events-form/events-form.component.ts
  GatorClubLife/src/app/permits/permits.component.ts
Labels: FE, Sprint 4

#162 Next Button
  GatorClubLife/src/app/events-form/events-form.component.css
  GatorClubLife/src/app/events-form/events-form.component.html
Labels: FE, Sprint 4

#164 Event-dates
  GatorClubLife/package-lock.json
  GatorClubLife/package.json
  GatorClubLife/src/app/app.component.ts
  GatorClubLife/src/app/app.routes.ts
  GatorClubLife/src/app/event-dates/event-dates.component.css
  GatorClubLife/src/app/event-dates/event-dates.component.html
  GatorClubLife/src/app/event-dates/event-dates.component.spec.ts
  GatorClubLife/src/app/event-dates/event-dates.component.ts
  GatorClubLife/src/app/events-form/events-form.component.html
  GatorClubLife/src/app/events-form/events-form.component.ts
  node_modules/.package-lock.json
  node_modules/@angular/animations/LICENSE
  node_modules/@angular/animations/README.md
  node_modules/@angular/animations/animation_driver.d-DZNLUjou.d.ts
  node_modules/@angular/animations/animation_player.d-CTCg5nkL.d.ts
  node_modules/@angular/animations/browser/index.d.ts
  node_modules/@angular/animations/browser/testing/index.d.ts
  node_modules/@angular/animations/fesm2022/animations.mjs
  node_modules/@angular/animations/fesm2022/animations.mjs.map
  node_modules/@angular/animations/fesm2022/browser.mjs
  node_modules/@angular/animations/fesm2022/browser.mjs.map
  node_modules/@angular/animations/fesm2022/browser/testing.mjs
  node_modules/@angular/animations/fesm2022/browser/testing.mjs.map
  node_modules/@angular/animations/fesm2022/private_export-CacKMzxJ.mjs
  node_modules/@angular/animations/fesm2022/private_export-CacKMzxJ.mjs.map
  node_modules/@angular/animations/fesm2022/util-DN3Vao_r.mjs
  node_modules/@angular/animations/fesm2022/util-DN3Vao_r.mjs.map
  node_modules/@angular/animations/index.d.ts
  node_modules/@angular/animations/package.json
  node_modules/fsevents/LICENSE
  node_modules/fsevents/README.md
  node_modules/fsevents/fsevents.d.ts
  node_modules/fsevents/fsevents.js
  node_modules/fsevents/fsevents.node
  node_modules/fsevents/package.json
  package-lock.json
Labels: FE, Sprint 4

#166 additional-forms
  GatorClubLife/src/app/additional-forms/additional-forms.component.css
  GatorClubLife/src/app/additional-forms/additional-forms.component.html
  GatorClubLife/src/app/additional-forms/additional-forms.component.spec.ts
  GatorClubLife/src/app/additional-forms/additional-forms.component.ts
  GatorClubLife/src/app/app.routes.ts
  GatorClubLife/src/app/event-dates/event-dates.component.css
  GatorClubLife/src/app/events-form/events-form.component.css
  GatorClubLife/src/app/events-form/events-form.component.html
Labels: FE, Sprint 4

#168 permits-review page
  GatorClubLife/src/app/additional-forms/additional-forms.component.css
  GatorClubLife/src/app/additional-forms/additional-forms.component.html
  GatorClubLife/src/app/app.routes.ts
  GatorClubLife/src/app/event-review/event-review.component.css
  GatorClubLife/src/app/event-review/event-review.component.html
  GatorClubLife/src/app/event-review/event-review.component.spec.ts
  GatorClubLife/src/app/event-review/event-review.component.ts
Labels: FE, Sprint 4

#170 event-review bug
  GatorClubLife/src/app/event-review/event-review.component.css
  GatorClubLife/src/app/event-review/event-review.component.html
Labels: bug, FE, Sprint 4

#172 Event Categories bug
  GatorClubLife/src/app/events-form/events-form.component.css
  GatorClubLife/src/app/events-form/events-form.component.html
  GatorClubLife/src/app/events-form/events-form.component.ts
Labels: bug, FE, Sprint 4

#174 background
  GatorClubLife/src/app/events-form/events-form.component.css
Labels: bug, FE, Sprint 4

#179 Added tables to store information about the event for the permits
  GatorClubLife/package-lock.json
  GatorClubLife/package.json
  backend/database/database.go
  gator_club_life.db
  gator_club_life.db-journal
Labels: BE, Sprint 4

#180 Created the EventPermit endpoint to store all the information upon submission
  backend/main.go
  backend/routes/EventPermits.go
Labels: BE, Sprint 4

#185 Connected the FE to BE for the Event Permit to be stored in the DB
  GatorClubLife/src/app/additional-forms/additional-forms.component.html
  GatorClubLife/src/app/additional-forms/additional-forms.component.ts
  GatorClubLife/src/app/event-dates/event-dates.component.ts
  GatorClubLife/src/app/event-review/event-review.component.ts
  GatorClubLife/src/app/events-form/events-form.component.html
  GatorClubLife/src/app/events-form/events-form.component.ts
  GatorClubLife/src/app/permits/permits.component.ts
  GatorClubLife/src/app/services/event-permit.service.ts
  gator_club_life.db
Labels: BE, FE, Sprint 4

#192 Updated the DB for MySubmissions
  backend/database/database.go
  gator_club_life.db
Labels: BE, Sprint 4

#193 Created API and updated Login API, created middleware to support adding SubmittedBy
  GatorClubLife/package-lock.json
  GatorClubLife/src/app/event-review/event-review.component.ts
  GatorClubLife/src/app/login/login.component.ts
  backend/database/database.go
  backend/main.go
  backend/middleware/session.go
  backend/routes/EventPermits.go
  backend/routes/login.go
  backend/routes/submissions.go
  gator_club_life.db
Labels: BE, Sprint 4

#194 FE My Submissions
  GatorClubLife/src/app/my-submissions/my-submissions.component.css
  GatorClubLife/src/app/my-submissions/my-submissions.component.html
  GatorClubLife/src/app/my-submissions/my-submissions.component.ts
Labels: FE, Sprint 4

#195 Created the BE code for MySubmissions
  backend/routes/login.go
  backend/routes/submissions.go
Labels: BE, Sprint 4

#198 Fixed the issue and ensured that the information summary reflects the DB
  GatorClubLife/package-lock 2.json
  GatorClubLife/src/app/additional-forms/additional-forms.component.ts
  GatorClubLife/src/app/event-dates/event-dates.component.ts
  GatorClubLife/src/app/event-review/event-review.component.html
  GatorClubLife/src/app/event-review/event-review.component.ts
  GatorClubLife/src/app/my-submissions/my-submissions.component.html
  GatorClubLife/src/app/my-submissions/my-submissions.component.ts
  GatorClubLife/src/app/services/event-permit.service.ts
  backend/main.go
  backend/routes/EventPermits.go
  gator_club_life.db
Labels: BE, FE, Sprint 4

#200 Implemented session destruction on backend restart and ensured a secure session flow
  GatorClubLife/src/app/announcements/announcements.component.ts
  GatorClubLife/src/app/auth.interceptor.spec.ts
  GatorClubLife/src/app/auth.interceptor.ts
  GatorClubLife/src/app/organization-details/organization-details.component.ts
  GatorClubLife/src/main.ts
  backend/main.go
  backend/middleware/RequireAuth.go
  backend/middleware/session.go
  backend/routes/login.go
  backend/routes/submissions.go
  gator_club_life.db
Labels: bug, BE, Sprint 4

#204 Events Learn More Page
  GatorClubLife/src/app/events/events.component.css
  GatorClubLife/src/app/events/events.component.html
  GatorClubLife/src/app/events/events.component.spec.ts
  GatorClubLife/src/app/events/events.component.ts
  GatorClubLife/src/index.html
Labels: FE, Sprint 4

#218 login bug
  backend/routes/login.go
Labels: bug, BE, FE, Sprint 4

#205 Unit Tests for Sprint 4
  backend/gator_club_life.db
  backend/middleware/middleware_test.go
  backend/routes/clubs_id_endpoints_test.go
  backend/routes/eventpermits_endpoints_test.go
  backend/routes/login_endpoints_test.go
  backend/testutils/test_router.go
Labels: BE, Unit Test, Sprint 4

#222 Back button bug
  GatorClubLife/src/app/event-dates/event-dates.component.ts
  gator_club_life.db
Labels: bug, BE, FE, Sprint 4

#225 Added Swagger Documentation for APIs
  backend/docs/docs.go
  backend/docs/swagger.json
  backend/docs/swagger.yaml
  backend/routes/EventPermits.go
  backend/routes/announcements.go
  backend/routes/clubs.go
  backend/routes/login.go
  backend/routes/logout.go
  backend/routes/submissions.go
  backend/routes/users.go
  gator_club_life.db
Labels: BE, Sprint 4

#226 Unit Tests
  GatorClubLife/src/app/about/about.component.spec.ts
  GatorClubLife/src/app/additional-forms/additional-forms.component.spec.ts
  GatorClubLife/src/app/announcements/announcements.component.spec.ts
  GatorClubLife/src/app/event-dates/event-dates.component.spec.ts
  GatorClubLife/src/app/event-review/event-review.component.spec.ts
  GatorClubLife/src/app/event-review/event-review.component.ts
  GatorClubLife/src/app/events-form/events-form.component.spec.ts
  GatorClubLife/src/app/login/login.component.spec.ts
  GatorClubLife/src/app/my-events/my-events.component.spec.ts
  GatorClubLife/src/app/my-profile/my-profile.component.spec.ts
  GatorClubLife/src/app/my-submissions/my-submissions.component.spec.ts
  GatorClubLife/src/app/organization-details/organization-details.component.spec.ts
  GatorClubLife/src/app/organizations/organizations.component.spec.ts
  GatorClubLife/src/app/permits/permits.component.spec.ts
Labels: FE, Sprint 4

#228 Completed cypress testing for FrontEnd work-flow
  GatorClubLife/cypress.config.ts
  GatorClubLife/cypress/e2e/full-permit-flow.cy.ts
  GatorClubLife/cypress/e2e/organizations.cy.ts
  GatorClubLife/cypress/e2e/register_spec.cy.ts
  GatorClubLife/cypress/e2e/spec.cy.ts
  GatorClubLife/cypress/screenshots/permits-visible-content (1).png
  GatorClubLife/cypress/screenshots/permits-visible-content.png
  GatorClubLife/cypress/support/commands.ts
  GatorClubLife/package-lock.json
  GatorClubLife/package.json
Labels: FE, Sprint 4, cypress
